"""Decision Recall deterministic core (Milestone 1)."""

from .domain import (
    AuthorizationDecision,
    AuthorizationStatus,
    CompositionState,
    CompositionValue,
    DecisionContract,
    EvidenceRecord,
    HistoricalKnowledgeState,
    HistoricalRelation,
    MatchResult,
    NumericObservation,
    RelationCandidate,
    RelationSlot,
    RelationType,
    RevisitResult,
    SafeReuseResult,
    SafeReuseTargetSpec,
    ThresholdCondition,
    CurrentMatchRule,
    RevisitRule,
    WorldEvent,
)
from .engine import (
    GuardViolation,
    authorize_historical_role,
    evaluate_current_match,
    evaluate_revisit,
    evaluate_safe_reuse,
    affected_rule_ids,
)

__all__ = [
    "AuthorizationDecision",
    "AuthorizationStatus",
    "CompositionState",
    "CompositionValue",
    "DecisionContract",
    "EvidenceRecord",
    "HistoricalKnowledgeState",
    "HistoricalRelation",
    "MatchResult",
    "NumericObservation",
    "RelationCandidate",
    "RelationSlot",
    "RelationType",
    "RevisitResult",
    "SafeReuseResult",
    "SafeReuseTargetSpec",
    "ThresholdCondition",
    "CurrentMatchRule",
    "RevisitRule",
    "WorldEvent",
    "GuardViolation",
    "authorize_historical_role",
    "evaluate_current_match",
    "evaluate_revisit",
    "evaluate_safe_reuse",
    "affected_rule_ids",
]
